### ISSUE TITLE
Moving into Testcontainers GitHub organisation

### ISSUE THREAD

**Issue by kiview** [testcontainers/testcontainers-hs#26]
Hi @alexbiehl and community,

I am one of the maintainers of [testcontainers-java](https://github.com/testcontainers/testcontainers-java) and we recently discovered your Testcontainers implementation. We were wondering if you are interested in moving the project under the Testcontainers organization. This might help with better discoverability within the community and we can also engage in a dialog about implementation details and best practices as identified in our other language implementations. Of course you keep the full control and admin permissions on the repository.

Let us know what you think, either here or by joining our [Slack](https://slack.testcontainers.org/).

**Comment by alexbiehl** [comment]
Hi @kiview, 

Sounds like a great idea! Will join Slack soon to talk about further steps.

**Comment by alexbiehl** [comment]
Done!
